# Generated by Django 4.0.4 on 2022-05-22 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
