# Generated by Django 4.0.4 on 2022-05-22 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elms', '0002_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('marks', models.FloatField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('marks', models.FloatField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='classtest',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='classtestsubmission',
            name='user',
        ),
        migrations.DeleteModel(
            name='assignment',
        ),
        migrations.DeleteModel(
            name='assignmentSubmission',
        ),
        migrations.DeleteModel(
            name='classTest',
        ),
        migrations.DeleteModel(
            name='classTestSubmission',
        ),
    ]
